export const genders = [
  { label: 'Male', value: 'male' },
  { label: 'Female', value: 'female' },
  { label: 'Transgender', value: 'transgender' }
];

export const timezones = [
  { label:"(GMT-12:00) International Date Line West", value:"UTC-12"},
  { label:"(GMT-11:00) Midway Island, Samoa", value:"UTC-11"},
  { label:"(GMT-10:00) Hawaii", value:"UTC-10"},
  { label:"(GMT-09:00) Alaska", value:"UTC-9"},
  { label:"(GMT-08:00) Pacific Time (US & Canada)", value:"UTC-8"},
  { label:"(GMT-08:00) Tijuana, Baja California", value:"UTC-8"},
  { label:"(GMT-07:00) Arizona", value:"UTC-7"},
  { label:"(GMT-07:00) Chihuahua, La Paz, Mazatlan", value:"UTC-7"},
  { label:"(GMT-07:00) Mountain Time (US & Canada)", value:"UTC-7"},
  { label:"(GMT-06:00) Central America", value:"UTC-6"},
  { label:"(GMT-06:00) Central Time (US & Canada)", value:"UTC-6"},
  { label:"(GMT-06:00) Guadalajara, Mexico City, Monterrey", value:"UTC-6"},
  { label:"(GMT-06:00) Saskatchewan", value:"UTC-6"},
  { label:"(GMT-05:00) Bogota, Lima, Quito, Rio Branco", value:"UTC-5"},
  { label:"(GMT-05:00) Eastern Time (US & Canada)", value:"UTC-5"},
  { label:"(GMT-05:00) Indiana (East)", value:"UTC-5"},
  { label:"(GMT-04:00) Atlantic Time (Canada)", value:"UTC-4"},
  { label:"(GMT-04:00) Caracas, La Paz", value:"UTC-4"},
  { label:"(GMT-04:00) Manaus", value:"UTC-4"},
  { label:"(GMT-04:00) Santiago", value:"UTC-4"},
  { label:"(GMT-03:30) Newfoundland", value:"UTC-3"},
  { label:"(GMT-03:00) Brasilia", value:"UTC-3"},
  { label:"(GMT-03:00) Buenos Aires, Georgetown", value:"UTC-3"},
  { label:"(GMT-03:00) Greenland", value:"UTC-3"},
  { label:"(GMT-03:00) Montevideo", value:"UTC-3"},
  { label:"(GMT-02:00) Mid-Atlantic", value:"UTC-2"},
  { label:"(GMT-01:00) Cape Verde Is.", value:"UTC-1"},
  { label:"(GMT-01:00) Azores", value:"UTC-1"},
  { label:"(GMT+00:00) Casablanca, Monrovia, Reykjavik", value:"UTC+0"},
  { label:"(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London", value:"UTC+0"},
  { label:"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", value:"UTC+1"},
  { label:"(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague", value:"UTC+1"},
  { label:"(GMT+01:00) Brussels, Copenhagen, Madrid, Paris", value:"UTC+1"},
  { label:"(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb", value:"UTC+1"},
  { label:"(GMT+01:00) West Central Africa", value:"UTC+1"},
  { label:"(GMT+02:00) Amman", value:"UTC+2"},
  { label:"(GMT+02:00) Athens, Bucharest, Istanbul", value:"UTC+2"},
  { label:"(GMT+02:00) Beirut", value:"UTC+2"},
  { label:"(GMT+02:00) Cairo", value:"UTC+2"},
  { label:"(GMT+02:00) Harare, Pretoria", value:"UTC+2"},
  { label:"(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", value:"UTC+2"},
  { label:"(GMT+02:00) Jerusalem", value:"UTC+2"},
  { label:"(GMT+02:00) Minsk", value:"UTC+2"},
  { label:"(GMT+02:00) Windhoek", value:"UTC+2"},
  { label:"(GMT+03:00) Kuwait, Riyadh, Baghdad", value:"UTC+3"},
  { label:"(GMT+03:00) Moscow, St. Petersburg, Volgograd", value:"UTC+3"},
  { label:"(GMT+03:00) Nairobi", value:"UTC+3"},
  { label:"(GMT+03:00) Tbilisi", value:"UTC+3"},
  { label:"(GMT+03:30) Tehran", value:"UTC+03:30"},
  { label:"(GMT+04:00) Abu Dhabi, Muscat", value:"UTC+4"},
  { label:"(GMT+04:00) Baku", value:"UTC+4"},
  { label:"(GMT+04:00) Yerevan", value:"UTC+4"},
  { label:"(GMT+04:30) Kabul", value:"UTC+04:30"},
  { label:"(GMT+05:00) Yekaterinburg", value:"UTC+5"},
  { label:"(GMT+05:00) Islamabad, Karachi, Tashkent", value:"UTC+5"},
  { label:"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi", value:"UTC+05:30"},
  { label:"(GMT+05:30) Sri Jayawardenapura", value:"UTC+05:30"},
  { label:"(GMT+05:45) Kathmandu", value:"UTC+05:45"},
  { label:"(GMT+06:00) Almaty, Novosibirsk", value:"UTC+6"},
  { label:"(GMT+06:00) Astana, Dhaka", value:"UTC+6"},
  { label:"(GMT+06:30) Yangon (Rangoon)", value:"UTC+06:30"},
  { label:"(GMT+07:00) Bangkok, Hanoi, Jakarta", value:"UTC+7"},
  { label:"(GMT+07:00) Krasnoyarsk", value:"UTC+7"},
  { label:"(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi", value:"UTC+8"},
  { label:"(GMT+08:00) Kuala Lumpur, Singapore", value:"UTC+8"},
  { label:"(GMT+08:00) Irkutsk, Ulaan Bataar", value:"UTC+8"},
  { label:"(GMT+08:00) Perth", value:"UTC+8"},
  { label:"(GMT+08:00) Taipei", value:"UTC+8"},
  { label:"(GMT+09:00) Osaka, Sapporo, Tokyo", value:"UTC+9"},
  { label:"(GMT+09:00) Seoul", value:"UTC+9"},
  { label:"(GMT+09:00) Yakutsk", value:"UTC+9"},
  { label:"(GMT+09:30) Adelaide", value:"UTC+09:30"},
  { label:"(GMT+09:30) Darwin", value:"UTC+09:30"},
  { label:"(GMT+10:00) Brisbane", value:"UTC+10"},
  { label:"(GMT+10:00) Canberra, Melbourne, Sydney", value:"UTC+10"},
  { label:"(GMT+10:00) Hobart", value:"UTC+10"},
  { label:"(GMT+10:00) Guam, Port Moresby", value:"UTC+10"},
  { label:"(GMT+10:00) Vladivostok", value:"UTC+10"},
  { label:"(GMT+11:00) Magadan, Solomon Is., New Caledonia", value:"UTC+11"},
  { label:"(GMT+12:00) Auckland, Wellington", value:"UTC+12"},
  { label:"(GMT+12:00) Fiji, Kamchatka, Marshall Is.", value:"UTC+12"},
  { label:"(GMT+13:00) Nuku'alofa", value:"UTC+13"}
];

export const languageLevels = [
  { label: 'Beginner', value: 'beginner'},
  { label: 'Intermediate', value: 'intermediate'},
  { label: 'Fluent', value: 'fluent'},
]